# Generated by Django 3.2.16 on 2024-04-17 12:54

from django.db import migrations, models

HF_VIEWS_TO_REMOVE = [
    "uvwAmountApproved",
    "uvwAmountClaimed",
    "uvwAmountRejected",
    "uvwAmountValuated",
    "uvwClaimEntered",
    "uvwClaimProcessed",
    "uvwClaimRejected",
    "uvwClaimSent",
    "uvwClaimSubmitted",
    "uvwClaimValuated",
    "uvwHospitalAdmissions",
    "uvwHospitalDays",
    "uvwItemExpenditures",
    "uvwItemUtilization",
    "uvwNumberFeedbackAnswerYes",
    "uvwNumberFeedbackResponded",
    "uvwNumberFeedbackSent",
    "uvwOverallAssessment",
    "uvwServiceExpenditures",
    "uvwServiceUtilization",
    "uvwVisit",
]


def delete_views():
    sql_str = ''
    for view in HF_VIEWS_TO_REMOVE:
        sql_str += f'DROP VIEW IF EXISTS "{view}";\n'
    return sql_str


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_set_managed_to_true'),
    ]

    operations = [
        migrations.RunSQL(delete_views(), migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='healthfacility',
            name='code',
            field=models.CharField(db_column='HFCode', max_length=50),
        ),
    ]
