# Generated by Django 3.2.16 on 2023-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_set_managed_to_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='code',
            field=models.CharField(db_column='HFCode', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, db_column='LocationCode', max_length=20, null=True),
        ),
    ]
