# Generated by Django 3.2.16 on 2023-12-05 18:13

from django.db import migrations, models


SPIMM_LEGAL_FORM_FOR_PROFIT = ("F", "For Profit")
SPIMM_LEGAL_FORM_NON_PROFIT = ("N", "Non-Profit")
SPIMM_LEGAL_FORM_EHO = ("E", "Ethnic Health Organization")
SPIMM_LEGAL_FORM_PUBLIC_FACILITY = ("U", "Public Facility")
SPIMM_LEGAL_FORMS = [
    SPIMM_LEGAL_FORM_EHO,
    SPIMM_LEGAL_FORM_NON_PROFIT,
    SPIMM_LEGAL_FORM_FOR_PROFIT,
    SPIMM_LEGAL_FORM_PUBLIC_FACILITY
]


def add_spimm_legal_forms(apps, schema_editor):
    HealthFacilityLegalForm = apps.get_model("location", "HealthFacilityLegalForm")
    for form in SPIMM_LEGAL_FORMS:
        HealthFacilityLegalForm.objects.create(
            code=form[0],
            legal_form=form[1],
        )


def remove_spimm_legal_forms(apps, schema_editor):
    HealthFacilityLegalForm = apps.get_model("location", "HealthFacilityLegalForm")
    codes = [form[0] for form in SPIMM_LEGAL_FORMS]
    spimm_legal_forms = HealthFacilityLegalForm.objects.filter(code__in=codes).all()
    for legal_form in spimm_legal_forms:
        legal_form.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_auto_20230724_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='spimm_contract_end_date',
            field=models.DateField(blank=True, db_column='SPIMMContractEndDate', null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='spimm_contract_start_date',
            field=models.DateField(blank=True, db_column='SPIMMContractStartDate', null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='email',
            field=models.TextField(blank=True, db_column='eMail', null=True),
        ),
        migrations.RunPython(add_spimm_legal_forms, remove_spimm_legal_forms)
    ]
